### ISSUE TITLE
A problem confusing

### ISSUE THREAD

**Issue by just12321** [tljxyys/Perspective-Unet#2]
I am confused by the following: Given that 
𝑞<sup>∗</sup>=𝑞𝜑<sup>𝑇</sup> and 𝑘<sup>∗</sup>=𝑘𝜑<sup>T</sup> , then:
𝑞<sup>*</sup>(𝑘<sup>∗</sup>)<sup>T</sup>=(𝑞𝜑<sup>T</sup>)(𝑘𝜑<sup>𝑇</sup>)<sup>T</sup>=𝑞𝜑<sup>𝑇</sup>(𝜑𝑘<sup>𝑇</sup>). Since φ is an orthogonal matrix, we have 𝜑<sup>T</sup>𝜑=𝐼. Therefore:
𝑞<sup>∗</sup>(𝑘<sup>∗</sup>)<sup>𝑇</sup>=𝑞𝑘<sup>𝑇</sup>.
 
What is the issue here? Or the 𝜑 just servers for 1/C(x) (namely the D_inv in the code)? Could someone please help to clarify!

**Comment by tljxyys** [comment]
𝜑 is not a mathematically orthogonal matrix, and it is not even a square matrix, so 𝜑T𝜑 = 𝐼 is not valid in this situation.

**Comment by tljxyys** [comment]
The “final_matrix” in the code is generated using multiple orthogonal matrix blocks (i.e., each block is an orthogonal matrix), but the fact that the final_matrix is stitched together and scaled does not guarantee that the entire final_matrix is still orthogonal.

**Comment by just12321** [comment]
> The “final_matrix” in the code is generated using multiple orthogonal matrix blocks (i.e., each block is an orthogonal matrix), but the fact that the final_matrix is stitched together and scaled does not guarantee that the entire final_matrix is still orthogonal.

Oh, I see, I review the code and notice that I've mistakenly thought nb_column and nb_row are H and W(=H) of the feature, thanks! 😘
